name: "cron_action"
on:
  schedule:
    - cron:  '*/5 * * * *'
env:
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
  CARGO_TERM_COLOR: always

jobs:
  singleJobName:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ github.sha }}

    - name: Run
      run: target/release/stayfolio-bot

